# Generated by Django 4.1.5 on 2023-01-19 13:23

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Сдам', 'Сдам,'), ('Продам', 'Продам'), ('Куплю', 'Куплю'), ('Сниму', 'Сниму')], max_length=15, verbose_name='Тип')),
                ('item_type', models.CharField(choices=[('Квартира', 'Квартира'), ('Дом', 'Дом'), ('Участок', 'Участок'), ('Гараж', 'Гараж'), ('Машиноместо', 'Машиноместо'), ('Коммерческая недвижимость', 'Коммерческая недвижимость')], max_length=50, verbose_name='Тип объекта')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('region', models.CharField(max_length=50, verbose_name='Регион')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улицы')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('total_floors', models.IntegerField(blank=True, null=True, verbose_name='Этажей всего')),
                ('material', models.CharField(choices=[('Кирпич', 'Кирпич'), ('Монолит', 'Монолит'), ('Блоки', 'Блоки'), ('Монолит+кирпич', 'Монолит+кирпич'), ('Дерево', 'Дерево'), ('Каркас', 'Каркас'), ('Саман', 'Саман'), ('Другое', 'Другое')], max_length=100, verbose_name='Материал стен')),
                ('total_surface', models.IntegerField(blank=True, null=True, verbose_name='Площадь общая')),
                ('livin_surface', models.IntegerField(blank=True, null=True, verbose_name='Площадь живая')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость')),
                ('trade', models.BooleanField(default=False, verbose_name='Возможность обмена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items_img/', verbose_name='Image')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='items_window.item')),
            ],
        ),
    ]
