# Generated by Django 4.1.5 on 2023-01-20 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('items_window', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities_light.region', verbose_name='Регион'),
        ),
    ]
